### ISSUE TITLE
report undefined meta variable

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#1064]
```[tasklist]
### Tasks
- [ ] https://github.com/ast-grep/ast-grep/issues/1065
- [ ] https://github.com/ast-grep/ast-grep/issues/1066
- [ ] https://github.com/ast-grep/ast-grep/issues/1067
- [ ] https://github.com/ast-grep/ast-grep/issues/1068
- [ ] https://github.com/ast-grep/ast-grep/issues/1069
- [ ] https://github.com/ast-grep/ast-grep/issues/1070
- [ ] https://github.com/ast-grep/ast-grep/issues/1080
```
