### ISSUE TITLE
[refactor] remove var_matcher from env

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#218]
Only rule with constraints use it

```[tasklist]
## Todo
- [x] Remove match_constraints from matcher
- [ ] Remove var_matchers from MetaVarEnv
- [x] Add constraints to RuleWithConstraints
- [x] Remove get_meta_var_env from matcher
```
